package com.zxc.mapper;

import com.zxc.entity.CfFans;
import com.zxc.entity.CfFansExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CfFansMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    long countByExample(CfFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int deleteByExample(CfFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int insert(CfFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int insertSelective(CfFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    List<CfFans> selectByExample(CfFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    CfFans selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CfFans record, @Param("example") CfFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CfFans record, @Param("example") CfFansExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CfFans record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_fans
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CfFans record);
}